### PR TITLE
KKRT Property-based testing for bit operations

### PR DESCRIPTION
**Pull request by xcapaldi**

### CODE REVIEW

**Review by juanli16 — CHANGES_REQUESTED** [review]
I would add the naive implementation of bit ops, and use `CheckEqual` for equality.
In addition, we can also test the properties of the operations. For instance in XOR, `xor(x, 0) == x` (identity), `xor(a, b) == xor(b, a)` (associativity), and `xor(x, 1)` is the same as flipping all the bits, and finally `xor(x, x) == 0`. 
For AND, `and(x, 1) == x`, `and(x, 0) == 0`, etc.
I think these property testing are more important since our protocol relies on those mathematical properties.

**Comment by xcapaldi** [comment]
Naive implementation is already implemented as part of the `Generate` method. Do you mean I shouldn't include them in an expected output struct? I agree about the other properties. I will add tests for them

**Comment by juanli16** [comment]
I don't think we should create a struct that includes all the other operations, now we are mixing table testing with PBT. I think generate should just generate a byte slice, and in each `Test{BitOperation` function, we implement tests to check equality of our bit operations with the naive ones, plus the property testing.

**Review by juanli16 — APPROVED** [review]
LGTM

**Pull request merged**
